{% set name = "tstoolbox" %}
{% set version = "108.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tstoolbox-{{ version }}.tar.gz
  sha256: 65eb16af0cdb746af5a039519f741b44f7f42d722c8d844bac8d0d4badceefc5

build:
  entry_points:
    - tstoolbox = tstoolbox.tstoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - cltoolbox >=1.0.0
    - dateparser
    - dill
    - hydroerr
    - numpy
    - pandas
    - pint !=0.21.*
    - pint-pandas
    - plottoolbox >=102.1.1
    - pydantic >=2.0.0
    - pydot
    - scikit-learn
    - scipy
    - six
    - sqlalchemy
    - statsmodels
    - tabulate

test:
  imports:
    - tstoolbox
  commands:
    - pip check
    - tstoolbox --help
  requires:
    - pip

about:
  home: https://pypi.org/project/tstoolbox/
  summary: Command line script and Python library to manipulate time series.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
