{% set name = "tstoolbox" %}
{% set version = "108.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tstoolbox-{{ version }}.tar.gz
  sha256: 80c963184033b280f9d01be0ee54f8f1174ba55805246cf018fc50a181d3b863

build:
  entry_points:
    - tstoolbox = tstoolbox.tstoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - cltoolbox >=1.0.0
    - dateparser
    - numpy <2 # [py<=3.9]
    - pandas
    - pint !=0.21.*
    - pint-pandas
    - plottoolbox >=105.1.1
    - pydantic >=2.0.0
    - scikit-learn
    - scipy
    - statsmodels
    - tabulate

test:
  imports:
    - tstoolbox
  commands:
    - pip check
    - tstoolbox --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/tstoolbox/
  summary: Command line script and Python library to manipulate time series.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
