schema_version: 1

context:
  name: tstoolbox
  version: "108.2.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: c430af68e2a263ef6c1987305dedd918cfdf73d526bece90523a2832e997492d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - tstoolbox = tstoolbox.tstoolbox:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - cltoolbox >=1.0.0
    - dateparser
    - hydroerr
    - numpy
    - openpyxl
    - pandas
    - pint !=0.21
    - pint-pandas
    - plottoolbox >=105.0.1
    - pydantic >=2.0.0
    - scikit-learn
    - scipy
    - statsmodels
    - tabulate

tests:
  - python:
      imports:
        - tstoolbox
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - tstoolbox --help

about:
  summary: Command line script and Python library to manipulate time series.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/tstoolbox/

extra:
  recipe-maintainers:
    - timcera
